version: "3.8"

volumes:
  db:

services:
  db:
    container_name: postgres
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
