openapi: "3.0.1"
info:
  version: "1"
  title: "Test server"
  description: "Just for testing"
paths:
  /ping:
    get:
      operationId: "get_ping"
      description: ""
      parameters: []
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValueResponse"
components:
  securitySchemes: {}
  schemas:
    ValueResponse:
      properties:
        value:
          nullable: false
          type: "string"
    ErrorResponse:
      type: object
      properties:
        status:
          nullable: false
          type: integer
        message:
          type: string
          nullable: false
