openapi: "3.0.1"
info:
  version: "1"
  title: "Test server"
  description: "Just for testing"
servers:
  - url: http://localhost:8080/api
    description: Local server
paths:
  /ping:
    get:
      operationId: "get_ping"
      description: ""
      parameters: []
      security:
        - jwt: []
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValueResponse"
  /login:
    post:
      description: 'Log in to the application'
      parameters: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/LoginBody"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /users/me:
    get:
      description: 'Get currently logged in user'
      parameters: []
      security:
        - jwt: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
  /users:
    get:
      description: ''
      parameters: []
      security:
        - jwt: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserResponse"
    post:
      description: 'Create a new user'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes: 
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ValueResponse:
      properties:
        value:
          nullable: false
          type: "string"
    ErrorResponse:
      type: object
      properties:
        status:
          nullable: false
          type: integer
        message:
          type: string
          nullable: false
      required:
        - status
        - message
    LoginBody:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    LoginResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    NewUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    UserResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string
          x-go-json-ignore: true
      required:
        - id
        - username
        - password
